<a href="https://colab.research.google.com/github/joannathom/Knowledge-Check-2/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('ufo_sighting_data.csv.zip')
df.head()

<ipython-input-173-8613cba83b24>:1: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('ufo_sighting_data.csv.zip')

,Date_time,city,state/province,country,UFO_shape,length_of_encounter_seconds,described_duration_of_encounter,description,date_documented,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

In [ ]:
print(df.shape)

(80332, 11)

In [175]:
df.columns

Index(['Date_time', 'city', 'state/province', 'country', 'UFO_shape',
       'length_of_encounter_seconds', 'described_duration_of_encounter',
       'description', 'date_documented', 'latitude', 'longitude'],
      dtype='object')

In [176]:
fixed_columns = {
    'Date_time':'DATE_TIME','city':'CITY', 'state/province': 'STATE/PROVINCE','country':'COUNTRY',
    'UFO_shape':'UFO_SHAPE',
    'length_of_encounter_seconds':'ENCOUNTER/SECONDS',
    'described_duration_of_encounter':'ENCOUNTER/DURATION DESCRIPTION',
    'description':'DESCRIPTION', 'date_documented' : 'DATE_DOCUMENTED','latitude': 'LATITUDE',
    'longitude': 'LONGITUDE'
}

df.rename(columns=fixed_columns,inplace=True)
df.columns

Index(['DATE_TIME', 'CITY', 'STATE/PROVINCE', 'COUNTRY', 'UFO_SHAPE',
       'ENCOUNTER/SECONDS', 'ENCOUNTER/DURATION DESCRIPTION', 'DESCRIPTION',
       'DATE_DOCUMENTED', 'LATITUDE', 'LONGITUDE'],
      dtype='object')

In [177]:
df.head()

,DATE_TIME,CITY,STATE/PROVINCE,COUNTRY,UFO_SHAPE,ENCOUNTER/SECONDS,ENCOUNTER/DURATION DESCRIPTION,DESCRIPTION,DATE_DOCUMENTED,LATITUDE,LONGITUDE
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

In [178]:
df.CITY.unique()

array(['san marcos', 'lackland afb', 'chester (uk/england)', ...,
       'calmar (canada)', 'aleksandrow (poland)', 'hamstead (hollyridge)'],
      dtype=object)

In [179]:
df[df.CITY.str.contains('null')].head()

,DATE_TIME,CITY,STATE/PROVINCE,COUNTRY,UFO_SHAPE,ENCOUNTER/SECONDS,ENCOUNTER/DURATION DESCRIPTION,DESCRIPTION,DATE_DOCUMENTED,LATITUDE,LONGITUDE
1972,10/15/1999 03:00,conconully (conconully lake),wa,us,light,1800,maybe 30 min.,A very bright light shined through the window ...,9/19/2002,48.5575,-119.748611
48252,6/13/2004 12:28,conconully,wa,us,disk,5,5 seconds,Saucer-shaped object appeared to move across s...,6/18/2004,48.5575,-119.748611

In [180]:
df.CITY.replace({'null':''}, regex=True,inplace=True)

In [181]:
df[df.CITY.str.contains('null')].head()

Empty DataFrame
Columns: [DATE_TIME, CITY, STATE/PROVINCE, COUNTRY, UFO_SHAPE, ENCOUNTER/SECONDS, ENCOUNTER/DURATION DESCRIPTION, DESCRIPTION, DATE_DOCUMENTED, LATITUDE, LONGITUDE]
Index: []

In [182]:
df.dropna()

,DATE_TIME,CITY,STATE/PROVINCE,COUNTRY,UFO_SHAPE,ENCOUNTER/SECONDS,ENCOUNTER/DURATION DESCRIPTION,DESCRIPTION,DATE_DOCUMENTED,LATITUDE,LONGITUDE
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611
5,10/10/1961 19:00,bristol,tn,us,sphere,300,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.595,-82.188889
7,10/10/1965 23:45,norwalk,ct,us,disk,1200,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.1175,-73.408333
...,...,...,...,...,...,...,...,...,...,...,...
80327,9/9/2013 21:15,nashville,tn,us,light,600.0,10 minutes,Round from the distance/slowly changing colors...,9/30/2013,36.165833,-86.784444
80328,9/9/2013 22:00,boise,id,us,circle,1200.0,20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...,9/30/2013,43.613611,-116.202500
80329,9/9/2013 22:00,napa,ca,us,other,1200.0,hour,Napa UFO&#44,9/30/2013,38.297222,-122.284444
80330,9/9/2013 22:20,vienna,va,us,circle,5.0,5 seconds,Saw a five gold lit cicular craft moving fastl...,9/30/2013,38.901111,-77.265556
80331,9/9/2013 23:00,edmond,ok,us,cigar,1020.0,17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...,9/30/2013,35.652778,-97.477778